server:
  port: 8081

spring:
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/product-db
    username: admin
    password: root
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format-sql: true
    show-sql: true
    propreties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect


