INSERT INTO SUPPLIER (ID, NAME) VALUES (1, 'ChipArt');
INSERT INTO SUPPLIER (ID, NAME) VALUES (2, 'Pichau');
INSERT INTO SUPPLIER (ID, NAME) VALUES (3, 'TerabyteShop');
INSERT INTO SUPPLIER (ID, NAME) VALUES (4, 'Kabum');

INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1, 'Placa mãe');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2, 'Fonte');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (3, 'Processadores');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (4, 'GPU');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY) VALUES (0, 'RTX 3060', 1, 4, 7);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY) VALUES (1, 'Ryzen 5 3600x', 2, 3, 12);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY) VALUES (2, 'Fonte coolermaster', 3, 2, 8);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY) VALUES (3, 'Asus a320', 4, 1, 9);


